### ISSUE TITLE
Working on ECON-325 Module 1 - Central Tendency 

### ISSUE THREAD

**Issue by amohaidly1996** [ubcecon/comet-project#22]

**Comment by amohaidly1996** [comment]
- [ ]  Category 2 the Boxplot, the third bullet points explains the whiskers it claims "The lines outside the box (called the “whiskers”) are the either the min and max, or 1.5 times the interquartile. Values which exceed this distance are drawn as points, and are described as “outliers”.     When I looked it up, I got a slightly different explanation which states "whiskers are used to represent the variability of the minimum, maximum and any outlier data points in comparison to the IQR" 
[https://builtin.com/data-science/boxplot](url) .  Is this the same ? 

- [ ] Category 2 or 4, exercise 3 says "graph the distribution of values of the wages variable..." Prior to exercise 3, there was no lesson on distribution, or are we just suppose to create a Box plot ?  

Everything else looks good.

**Comment by jlgraves-ubc** [comment]
Great stuff; I'll let @oliverxjy organize fixing these issues.

**Comment by oliverxjy** [comment]
@jlgraves-ubc @amohaidly1996 

Thank you @amohaidly1996  for the great feedback!

1. Our original statement is specifically referring to how the whiskers are drawn by default in R's `boxplot()` function, while the online source provided is providing a more general understanding of what whiskers represent in a boxplot, without being specific to R's default implementation.  The third bullet point is also specifically within the context of "variety of different variations of the boxplot, but in R the default to create a diagram where:". We could discuss if we should include a more general definition of whiskers in addition to our R-specific definition in the notebook.
2. Yes, the idea is to guide students to use boxplot. Although there's no explicit lesson on distribution. The notebooks tries to implicitly guide students through. For example, we mentioned in the notebook : "Quantiles are equally divided sections of a distribution of values which together capture the full distribution of these values". We then introduce the concept of boxplot which is designed to visualize five number summary (quantiles). We could discuss if we should make the lesson of distribution more explicit rather than implicit.
